<?php

namespace App\Imports;

use App\Models\Identity;
use App\Models\Institution;
use App\Models\StudyProgram;
use App\Models\User;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class SintaAuthorImport implements ToCollection, WithHeadingRow
{
    public function __construct(
        protected bool $updateExisting = true
    ) {}

    public function headingRow(): int
    {
        return 5;
    }

    public function collection(Collection $rows)
    {
        foreach ($rows as $row) {
            // Using array keys based on the Excel header "slugs" generated by Maatwebsite Excel
            // You might need to adjust these keys if the slug generation is different
            $sintaId = (string) ($row['sinta_id'] ?? $row['sintaid'] ?? null);
            $nidn = (string) ($row['nidn'] ?? null);
            $name = $row[' nama'] ?? $row['nama'] ?? null; // Handle potential leading space in header

            if (! $nidn || ! $name) {
                continue;
            }

            // Extract Academic Profile
            $lastEducation = $row['pendidikan_terakhir'] ?? null;
            $functionalPos = $row['jabatan_fungsional'] ?? null;
            $titlePrefix = $row['gelar_depan'] ?? null;
            $titleSuffix = $row['gelar_belakang'] ?? null;

            // Extract SINTA Scores
            $sintaScoreV2Overall = $this->parseNumber($row['sinta_score_overall_versi_2'] ?? 0);
            $sintaScoreV23Yr = $this->parseNumber($row['sinta_score_3yr_versi_2'] ?? 0);
            $sintaScoreV3Overall = $this->parseNumber($row['sinta_score_overall_versi_3'] ?? 0);
            $sintaScoreV33Yr = $this->parseNumber($row['sinta_score_3yr_versi_3'] ?? 0);
            $affilScoreV3Overall = $this->parseNumber($row['afiliasi_score_overall_versi_3'] ?? 0);
            $affilScoreV33Yr = $this->parseNumber($row['afiliasi_score_3yr_versi_3'] ?? 0);

            // Extract Indexing Metrics
            $scopusDocs = $this->parseNumber($row['dokumen_scopus'] ?? 0);
            $scopusCitations = $this->parseNumber($row['sitasi_scopus'] ?? 0);
            $scopusCitedDocs = $this->parseNumber($row['dokumen_tersitasi_scopus'] ?? 0);
            $scopusHIndex = $this->parseNumber($row['h_index_scopus'] ?? 0);
            $scopusGIndex = $this->parseNumber($row['g_index_scopus'] ?? 0);
            $scopusI10Index = $this->parseNumber($row['i10_index_scopus'] ?? 0);

            $gsDocs = $this->parseNumber($row['dokumen_gs'] ?? 0);
            $gsCitations = $this->parseNumber($row['sitasi_gs'] ?? 0);
            $gsCitedDocs = $this->parseNumber($row['dokumen_tersitasi_gs'] ?? 0);
            $gsHIndex = $this->parseNumber($row['h_index_gs'] ?? 0);
            $gsGIndex = $this->parseNumber($row['g_index_gs'] ?? 0);
            $gsI10Index = $this->parseNumber($row['i10_index_gs'] ?? 0);

            $wosDocs = $this->parseNumber($row['dokumen_wos'] ?? 0);
            $wosCitations = $this->parseNumber($row['sitasi_wos'] ?? 0);
            $wosCitedDocs = $this->parseNumber($row['dokumen_tersitasi_wos'] ?? 0);
            $wosHIndex = $this->parseNumber($row['h_index_wos'] ?? 0);
            $wosGIndex = $this->parseNumber($row['g_index_wos'] ?? 0);
            $wosI10Index = $this->parseNumber($row['i10_index_wos'] ?? 0);

            $garudaDocs = $this->parseNumber($row['dokumen_garuda'] ?? 0);
            $garudaCitations = $this->parseNumber($row['sitasi_garuda'] ?? 0);
            $garudaCitedDocs = $this->parseNumber($row['dokumen_tersitasi_garuda'] ?? 0);

            $statusAktif = $row['status_aktif'] ?? 'Aktif';

            // Prepare Data Array
            $identityData = [
                'sinta_id' => $sintaId,
                'identity_id' => $nidn,
                // Academic Profile
                'last_education' => $lastEducation,
                'functional_position' => $functionalPos,
                'title_prefix' => $titlePrefix,
                'title_suffix' => $titleSuffix,
                // SINTA Scores
                'sinta_score_v2_overall' => $sintaScoreV2Overall,
                'sinta_score_v2_3yr' => $sintaScoreV23Yr,
                'sinta_score_v3_overall' => $sintaScoreV3Overall,
                'sinta_score_v3_3yr' => $sintaScoreV33Yr,
                'affil_score_v3_overall' => $affilScoreV3Overall,
                'affil_score_v3_3yr' => $affilScoreV33Yr,
                // Scopus
                'scopus_documents' => $scopusDocs,
                'scopus_citations' => $scopusCitations,
                'scopus_cited_documents' => $scopusCitedDocs,
                'scopus_h_index' => $scopusHIndex > 0 ? $scopusHIndex : null,
                'scopus_g_index' => $scopusGIndex,
                'scopus_i10_index' => $scopusI10Index,
                // Google Scholar
                'gs_documents' => $gsDocs,
                'gs_citations' => $gsCitations,
                'gs_cited_documents' => $gsCitedDocs,
                'gs_h_index' => $gsHIndex > 0 ? $gsHIndex : null,
                'gs_g_index' => $gsGIndex,
                'gs_i10_index' => $gsI10Index,
                // WoS
                'wos_documents' => $wosDocs,
                'wos_citations' => $wosCitations,
                'wos_cited_documents' => $wosCitedDocs,
                'wos_h_index' => $wosHIndex > 0 ? $wosHIndex : null,
                'wos_g_index' => $wosGIndex,
                'wos_i10_index' => $wosI10Index,
                // Garuda
                'garuda_documents' => $garudaDocs,
                'garuda_citations' => $garudaCitations,
                'garuda_cited_documents' => $garudaCitedDocs,
                // Status
                'is_active' => $statusAktif,
            ];

            // Mapping Study Program (Prodi)
            $prodiName = $row['prodi'] ?? null;
            if ($prodiName) {
                // Try to find Study Program
                $studyProgram = StudyProgram::where('name', 'like', '%'.$prodiName.'%')->first();
                if ($studyProgram) {
                    $identityData['study_program_id'] = $studyProgram->id;
                    $identityData['faculty_id'] = $studyProgram->faculty_id; // Set faculty if known
                }
            }

            // Selalu tetapkan institution default jika ada
            $defaultInstitution = Institution::first();
            if ($defaultInstitution) {
                $identityData['institution_id'] = $defaultInstitution->id;
            }

            // Logic: Upsert User & Identity
            // 1. Find Identity by ID (NIDN)
            $identity = Identity::where('identity_id', $nidn)->first();

            if ($identity) {
                // Update Existing Identity (Ini akan mengupdate skor, prodi, dan institusi)
                $identity->update($identityData);
            } else {
                // Create New User first if not exists
                // Use NIDN as email prefix if not provided
                $email = $nidn.'@lecturer.itsnu.ac.id';

                $user = User::where('email', $email)->first();
                if (! $user) {
                    $user = User::create([
                        'name' => $name,
                        'email' => $email,
                        'password' => Hash::make('password'),
                        'email_verified_at' => now(),
                    ]);
                    $user->assignRole('dosen');
                }

                $identityData['user_id'] = $user->id;
                $identityData['type'] = 'dosen';

                Identity::create($identityData);
            }
        }
    }

    private function parseNumber($value)
    {
        if (is_null($value)) {
            return 0;
        }

        // Remove non-numeric chars except dot and comma
        // Handle typically Indonesian/English number formats if messy
        return (float) $value;
    }
}
